# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c806b53a212a1a2f9a3a51c881f632689c4420ac19a96603d5c4f9463eda33edea0ea37f8b1638b076aecabe2006fdff5781b22065a817d8bd1df77294501fea
  consumer_key: <%= ENV["FTT_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["FTT_CONSUMER_SECRET"] %>
  access_token: <%= ENV["FTT_ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["FTT_ACCESS_TOKEN_SECRET"] %>

test:
  secret_key_base: c806b53a212a1a2f9a3a51c881f632689c4420ac19a96603d5c4f9463eda33edea0ea37f8b1638b076aecabe2006fdff5781b22065a817d8bd1df77294501fea
  consumer_key: <%= ENV["FTT_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["FTT_CONSUMER_SECRET"] %>
  access_token: <%= ENV["FTT_ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["FTT_ACCESS_TOKEN_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  access_token: <%= ENV["ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
